SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO


/* CREATED BY DF627 on 23-05-24 FOR DISPLAYING MISSING TABLES WHICH DOES NOT EXIST ANYMORE */

CREATE PROC [dbo].[GetMissingTbl]
AS
BEGIN

SELECT * FROM DBO.MissingTbl 
WHERE CAST(ProcessDate AS DATE)=DATEADD(DD,-1,CAST(GETDATE() AS DATE))
ORDER BY SpName

END
GO