SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

/*  CREATED BY DF627 ON 23-05-24 FOR THE PURPOSE OF DISPLAYING TOTAL LINE OF CODE OF THE STORED PROC */

CREATE PROC [dbo].[GetSpLineCnt]
AS
BEGIN
   
    -- Select all records from SpTotalLineCnt table
    SELECT * FROM DBO.SpTotalLineCnt
	WHERE CAST(ProcessDate AS DATE)=DATEADD(DD,-1,CAST(GETDATE() AS DATE))
	ORDER BY Object_Name 
END;


GO