SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

/* CREATED BY DF627 on 23-05-24 FOR DISPLAYING THE CURRENTLY EXECUTING QUERIES WITHIN THE SQL SERVER INSTANCE   */

create PROC [dbo].[GetBlockCommand]
AS
BEGIN

--Retrieving the records from the below table

SELECT * FROM DBO.SpBlock
WHERE CAST(StartTime AS DATE)=CAST(GETDATE() AS DATE)
ORDER BY StartTime DESC

END
GO