CREATE TABLE [CURDAT].[AdvFacSmartFinDetail] (
  [EntityKey] [bigint] IDENTITY,
  [AccountEntityId] [int] NOT NULL,
  [ECFSBRANCHCODE] [varchar](20) NULL,
  [ECFSREFCUSTOMERID] [varchar](50) NULL,
  [ECFSSourceSystemCustomerID] [varchar](50) NULL,
  [ECFSCUSTOMERACID] [varchar](50) NULL,
  [ECFSContractRefNo] [varchar](50) NULL,
  [ECFSACOPENDT] [date] SPARSE NULL,
  [ECFSProductCode] [varchar](20) NULL,
  [ECFSACTSEGMENTCODE] [varchar](20) NULL,
  [ECFSCURRENTLIMIT] [decimal](16, 2) SPARSE NULL,
  [ECFSCURRENTLIMITDT] [date] SPARSE NULL,
  [ECFSCURRENCYCODE] [varchar](20) NULL,
  [ECFSDrawingPower] [decimal](16, 2) SPARSE NULL,
  [ECFSBALANCE] [decimal](16, 2) SPARSE NULL,
  [ECFSPRINCOUTSTD] [decimal](16, 2) SPARSE NULL,
  [ECFSMAXDPD] [int] SPARSE NULL,
  [ECFSOVERDUEAMT] [decimal](16, 2) SPARSE NULL,
  [ECFSOVERDUESINCEDT] [date] SPARSE NULL,
  [ECFSPRINCOVERDUE] [decimal](16, 2) SPARSE NULL,
  [ECFSPRINCOVERDUESINCEDT] [date] SPARSE NULL,
  [ECFSINTOVERDUE] [decimal](16, 2) SPARSE NULL,
  [ECFSINTOVERDUESINCEDT] [date] SPARSE NULL,
  [ECFSOTHEROVERDUE] [decimal](16, 2) SPARSE NULL,
  [ECFSFIRSTDTOFDISB] [date] SPARSE NULL,
  [ECFSINTTRATE] [decimal](16, 8) SPARSE NULL,
  [ECFSAssetClass] [varchar](20) NULL,
  [AuthorisationStatus] [varchar](2) NULL,
  [EffectiveFromTimeKey] [int] NOT NULL,
  [EffectiveToTimeKey] [int] NOT NULL,
  [CreatedBy] [varchar](20) NULL,
  [DateCreated] [smalldatetime] NULL,
  [ModifiedBy] [varchar](20) NULL,
  [DateModified] [smalldatetime] NULL,
  [ApprovedBy] [varchar](20) NULL,
  [DateApproved] [smalldatetime] NULL,
  [D2Ktimestamp] [timestamp]
)
ON [PRIMARY]
GO