CREATE TABLE [DataUpload].[MocAccountDataUpload] (
  [Entitykey] [int] IDENTITY,
  [MocAccountDataEntityId] [int] NULL,
  [CustomerID] [varchar](50) NULL,
  [SourceSystemCustomerID] [varchar](50) NULL,
  [CustomerAcID] [varchar](30) NULL,
  [CustomerName] [varchar](225) NULL,
  [Balance] [decimal](18, 2) NULL,
  [IntrestReversal] [decimal](18, 2) NULL,
  [AdditionalProvision] [decimal](6, 2) NULL,
  [AdditionalProvisionAmount] [decimal](18, 2) NULL,
  [AppropriateSecurity] [char](1) NULL,
  [FITL] [char](1) NULL,
  [DFVAmount] [decimal](18, 2) NULL,
  [RepossessionDate] [date] NULL,
  [RestructureDate] [date] NULL,
  [OriginalDCCODate] [date] NULL,
  [ExtendedDCCODate] [date] NULL,
  [ActualDCCODate] [date] NULL,
  [Infrastructure] [char](1) NULL,
  [MOCReason] [varchar](500) NULL,
  [AuthorisationStatus] [varchar](2) NULL,
  [EffectiveFromTimeKey] [int] NULL,
  [EffectiveToTimeKey] [int] NULL,
  [CreatedBy] [varchar](20) NULL,
  [DateCreated] [smalldatetime] NULL,
  [ModifiedBy] [varchar](20) NULL,
  [DateModified] [smalldatetime] NULL,
  [ApprovedBy] [varchar](20) NULL,
  [DateApproved] [smalldatetime] NULL,
  [D2Ktimestamp] [timestamp],
  [ScreenFlag] [char](1) NULL
)
ON [PRIMARY]
GO