CREATE TABLE [dbo].[accountdata] (
  [AccountBranchCode] [varchar](10) NULL,
  [FCR_CustomerID] [varchar](30) NULL,
  [SourceSystemCustomerID] [varchar](30) NULL,
  [AccountID] [varchar](30) NULL,
  [ContractRefNo] [varchar](50) NULL,
  [AccountOpenDate] [date] NULL,
  [FacilityCodeLineCode] [varchar](30) NULL,
  [FacilityLine] [varchar](100) NULL,
  [ProductCode] [varchar](30) NULL,
  [SectorCode] [varchar](30) NULL,
  [AccountSegmentCode] [varchar](30) NULL,
  [CurrentLimit] [decimal](16, 2) NULL,
  [DisbAmount] [decimal](16, 2) NULL,
  [CurrentLimitDate] [date] NULL,
  [CurrencyCode] [varchar](10) NULL,
  [DrawingPower] [decimal](16, 2) NULL,
  [TotalBalanceOutstandingINR] [decimal](16, 2) NULL,
  [BalanceInCurrency] [decimal](16, 2) NULL,
  [PrincipalOutstanding] [decimal](16, 2) NULL,
  [MaxDPD] [int] NULL,
  [TotalOverdueAmount ] [decimal](16, 2) NULL,
  [OverdueSinceDate] [date] NULL,
  [PrincipalOverdue] [decimal](16, 2) NULL,
  [PrincipalOverdueSinceDate] [date] NULL,
  [PrincipalOverdueDPD] [int] NULL,
  [InterestOverdue] [decimal](16, 2) NULL,
  [InterestOverdueSinceDate] [date] NULL,
  [InterestOverdueSinceDPD] [int] NULL,
  [OtherOverdue] [decimal](16, 2) NULL,
  [OtherOverdueSinceDate] [date] NULL,
  [OtherOverdueSinceDPD] [int] NULL,
  [SbaCaaTodDate] [date] NULL,
  [LastCreditDate] [date] NULL,
  [ContinuousExcessSinceDate] [date] NULL,
  [DPD_CCOD] [int] NULL,
  [FirstDtOfDisb] [date] NULL,
  [InterestRate] [decimal](11, 8) NULL,
  [StockStatementDate] [date] NULL,
  [GovernmentGuaranteeAmount ] [decimal](16, 2) NULL,
  [WriteOffAmount] [decimal](16, 2) NULL,
  [UnAdjustSubSidy] [decimal](16, 2) NULL,
  [AssetClass] [varchar](20) NULL,
  [NPADate] [date] NULL,
  [SourceSystemName] [varchar](30) NULL,
  [RelationshipNumber] [varchar](30) NULL,
  [AccountFlag] [varchar](20) NULL,
  [CommercialFlag] [varchar](20) NULL,
  [Liability] [varchar](20) NULL,
  [CD] [int] NULL,
  [Accountstatus] [varchar](30) NULL,
  [AccountBlkCode1] [varchar](25) NULL,
  [AccountBlkCode2] [varchar](25) NULL,
  [DateOfData] [date] NULL,
  [Data_Date] [date] NULL,
  [Etl_Date] [date] NULL
)
ON [PRIMARY]
GO