CREATE TABLE [dbo].[AdvFacBillDetail_Mod] (
  [EntityKey] [int] IDENTITY,
  [AccountEntityId] [int] NOT NULL,
  [D2KFacilityID] [int] NULL,
  [BillNo] [varchar](100) NULL,
  [BillDt] [date] NULL,
  [BillAmt] [decimal](16, 2) NULL,
  [BillRefNo] [varchar](100) NULL,
  [BillPurDt] [date] NULL,
  [AdvAmount] [decimal](16, 2) NULL,
  [BillDueDt] [date] NULL,
  [BillExtendedDueDt] [date] NULL,
  [CrystalisationDt] [date] NULL,
  [CommercialisationDt] [date] NULL,
  [BillNatureAlt_Key] [smallint] NULL,
  [BillAcceptanceDt] [date] NULL,
  [UsanceDays] [smallint] NULL,
  [DraweeNo] [smallint] NULL,
  [DraweeBankName] [varchar](50) NULL,
  [DrawerName] [varchar](50) NULL,
  [PayeeName] [varchar](50) NULL,
  [CollectingBankName] [varchar](50) NULL,
  [CollectingBranchPlace] [varchar](50) NULL,
  [InterestIncome] [decimal](16, 2) NULL,
  [Commission] [decimal](16, 2) NULL,
  [DiscountCharges] [decimal](16, 2) NULL,
  [DelayedInt] [decimal](16, 2) NULL,
  [MarginType] [smallint] NULL,
  [MarginAmt] [decimal](16, 2) NULL,
  [CountryAlt_Key] [smallint] NULL,
  [BillOsReasonAlt_Key] [smallint] NULL,
  [CommodityAlt_Key] [smallint] NULL,
  [LcNo] [varchar](20) NULL,
  [LcAmt] [decimal](16, 2) NULL,
  [LcIssuingBankAlt_Key] [smallint] NULL,
  [LcIssuingBank] [varchar](50) NULL,
  [CurrencyAlt_Key] [smallint] NULL,
  [Balance] [decimal](16, 2) NULL,
  [BalanceInCurrency] [decimal](16, 4) NULL,
  [Overdue] [decimal](16, 2) NULL,
  [DerecognisedInterest1] [decimal](16, 2) NULL,
  [DerecognisedInterest2] [decimal](16, 2) NULL,
  [UnAppliedIntt] [decimal](16, 2) NULL,
  [BillFacilityNo] [int] NULL,
  [CAD] [decimal](16, 2) NULL,
  [CADU] [decimal](16, 2) NULL,
  [OverDueSinceDt] [date] NULL,
  [TotalProv] [decimal](16, 2) NULL,
  [AdditionalProv] [decimal](16, 2) NULL,
  [GenericAddlProv] [decimal](16, 2) NULL,
  [Secured] [decimal](16, 2) NULL,
  [CoverGovGur] [decimal](16, 2) NULL,
  [Unsecured] [decimal](16, 2) NULL,
  [Provsecured] [decimal](16, 2) NULL,
  [ProvUnsecured] [decimal](16, 2) NULL,
  [ProvDicgc] [decimal](16, 2) NULL,
  [npadt] [date] NULL,
  [ClaimType] [varchar](8) NULL,
  [ClaimCoverAmt] [decimal](16, 2) NULL,
  [ClaimLodgedDt] [date] NULL,
  [ClaimLodgedAmt] [decimal](16, 2) NULL,
  [ClaimRecvDt] [date] NULL,
  [ClaimReceivedAmt] [decimal](16, 2) NULL,
  [ClaimRate] [decimal](16, 2) NULL,
  [ScrCrError] [varchar](100) NULL,
  [RefSystemAcid] [varchar](30) NULL,
  [AdjDt] [date] NULL,
  [AdjReasonAlt_Key] [smallint] NULL,
  [EntityClosureDate] [date] NULL,
  [EntityClosureReasonAlt_Key] [smallint] NULL,
  [AuthorisationStatus] [varchar](2) NULL,
  [EffectiveFromTimeKey] [int] NULL,
  [EffectiveToTimeKey] [int] NULL,
  [CreatedBy] [varchar](20) NULL,
  [DateCreated] [smalldatetime] NULL,
  [ModifiedBy] [varchar](20) NULL,
  [DateModified] [smalldatetime] NULL,
  [ApprovedBy] [varchar](20) NULL,
  [DateApproved] [smalldatetime] NULL,
  [D2Ktimestamp] [timestamp],
  [MocStatus] [char](1) NULL,
  [MocDate] [smalldatetime] NULL,
  [MocTypeAlt_Key] [int] NULL,
  [ScrCrErrorSeq] [varchar](200) NULL,
  [ConsigmentExport] [char](1) NULL,
  [ChangeFields] [varchar](250) NULL,
  [OverDueInterest] [decimal](16, 2) NULL,
  [OverDuePenalInterest] [decimal](16, 2) NULL,
  [BillLimit] [decimal](16, 2) NULL,
  [IntCalDt] [date] NULL,
  [LbID] [int] NULL
)
ON [PRIMARY]
GO