CREATE TABLE [dbo].[AdvCustNPAdetailPRO] (
  [EntityKey] [int] NULL,
  [CustomerEntityId] [int] NULL,
  [Cust_AssetClassAlt_Key] [int] NULL,
  [NPADt] [datetime2] NULL,
  [LastInttChargedDt] [nvarchar](50) NULL,
  [DbtDt] [nvarchar](50) NULL,
  [LosDt] [nvarchar](50) NULL,
  [DefaultReason1Alt_Key] [nvarchar](50) NULL,
  [DefaultReason2Alt_Key] [nvarchar](50) NULL,
  [StaffAccountability] [nvarchar](50) NULL,
  [LastIntBooked] [nvarchar](50) NULL,
  [RefCustomerID] [nvarchar](50) NULL,
  [AuthorisationStatus] [nvarchar](50) NULL,
  [EffectiveFromTimeKey] [int] NULL,
  [EffectiveToTimeKey] [int] NULL,
  [CreatedBy] [nvarchar](50) NULL,
  [DateCreated] [datetime2] NULL,
  [ModifiedBy] [nvarchar](50) NULL,
  [DateModified] [nvarchar](50) NULL,
  [ApprovedBy] [nvarchar](50) NULL,
  [DateApproved] [nvarchar](50) NULL,
  [D2Ktimestamp] [nvarchar](50) NULL,
  [MocStatus] [nvarchar](50) NULL,
  [MocDate] [nvarchar](50) NULL,
  [MocTypeAlt_Key] [nvarchar](50) NULL,
  [WillfulDefault] [nvarchar](50) NULL,
  [WillfulDefaultReasonAlt_Key] [nvarchar](50) NULL,
  [WillfulRemark] [nvarchar](50) NULL,
  [WillfulDefaultDate] [nvarchar](50) NULL,
  [NPA_Reason] [nvarchar](100) NULL,
  [SourceSystemCustomerID] [nvarchar](50) NULL,
  [COVID] [nvarchar](50) NULL
)
ON [PRIMARY]
GO