CREATE TABLE [dbo].[DimLineCodeReview_Mod] (
  [ReviewLineCode_Key] [smallint] IDENTITY,
  [ReviewLineCodeAlt_Key] [smallint] NOT NULL,
  [ReviewLineCode] [varchar](20) NULL,
  [ReviewLineCodeName] [varchar](200) NULL,
  [ReviewLineCodeShortName] [varchar](20) NULL,
  [ReviewLineCodeShortNameEnum] [varchar](20) NULL,
  [ReviewLineCodeGroup] [varchar](50) NULL,
  [ReviewLineCodeSubGroup] [varchar](50) NULL,
  [ReviewLineCodeSegment] [varchar](50) NULL,
  [ReviewLineCodeValidCode] [char](1) NULL,
  [SrcSysReviewLineCodeCode] [varchar](50) NULL,
  [SrcSysReviewLineCodeName] [varchar](50) NULL,
  [DestSysReviewLineCodeCode] [varchar](10) NULL,
  [AssetNorm] [varchar](10) NULL,
  [AuthorisationStatus] [varchar](2) NULL,
  [EffectiveFromTimeKey] [int] NULL,
  [EffectiveToTimeKey] [int] NULL,
  [CreatedBy] [varchar](20) NULL,
  [DateCreated] [smalldatetime] NULL,
  [ModifiedBy] [varchar](20) NULL,
  [DateModified] [smalldatetime] NULL,
  [ApprovedBy] [varchar](20) NULL,
  [DateApproved] [smalldatetime] NULL,
  [Remarks] [varchar](1000) NULL,
  [ChangeFields] [varchar](250) NULL,
  [ApprovedByFirstLevel] [varchar](50) NULL,
  [DateApprovedFirstLevel] [datetime] NULL,
  [D2Ktimestamp] [timestamp],
  [CodeType] [varchar](50) NULL,
  [UploadID] [int] NULL,
  [ScreenFlag] [varchar](2) NULL
)
ON [PRIMARY]
GO