CREATE TABLE [dbo].[Dimuserinfo_mod_20220524] (
  [EntityKey] [int] IDENTITY,
  [UserLoginID] [varchar](20) NULL,
  [UserName] [varchar](50) NULL,
  [LoginPassword] [varchar](max) NULL,
  [PasswordChanged] [char](1) NULL,
  [PasswordChangeDate] [date] NULL,
  [ChangePwdCnt] [smallint] NULL,
  [UserLocation] [varchar](10) NULL,
  [UserLocationCode] [varchar](10) NULL,
  [UserRoleAlt_Key] [smallint] NULL,
  [SuspendedUser] [char](1) NULL,
  [CurrentLoginDate] [date] NULL,
  [ResetDate] [date] NULL,
  [Activate] [char](1) NULL,
  [UserLogged] [bit] NULL,
  [UserDeletionReasonAlt_Key] [int] NULL,
  [SystemLogOut] [bit] NULL,
  [EmployeeID] [varchar](20) NULL,
  [UserType] [varchar](20) NULL,
  [IsEmployee] [char](1) NULL,
  [IsChecker] [char](1) NULL,
  [RBIFLAG] [char](1) NULL,
  [DeptGroupCode] [varchar](10) NULL,
  [Email_ID] [varchar](200) NULL,
  [SecuritQsnAlt_Key] [int] NULL,
  [SecurityAns] [varchar](200) NULL,
  [MenuId] [varchar](max) NULL,
  [AuthorisationStatus] [varchar](2) NULL,
  [EffectiveFromTimeKey] [int] NULL,
  [EffectiveToTimeKey] [int] NULL,
  [CreatedBy] [varchar](20) NULL,
  [DateCreated] [smalldatetime] NULL,
  [ModifyBy] [varchar](20) NULL,
  [DateModified] [smalldatetime] NULL,
  [ApprovedBy] [varchar](20) NULL,
  [DateApproved] [smalldatetime] NULL,
  [D2Ktimestamp] [timestamp],
  [MIS_APP_USR_ID] [varchar](20) NULL,
  [MIS_APP_USR_PASS] [varchar](max) NULL,
  [UserLocationExcel] [varchar](100) NULL,
  [DesignationAlt_Key] [smallint] NULL,
  [MobileNo] [varchar](max) NULL,
  [IsCMA] [char](1) NULL,
  [Remark] [varchar](500) NULL,
  [SSOUse] [char](1) NULL,
  [SessionId] [int] NULL,
  [DimUserInfo] [int] NULL,
  [ProffEntityId] [int] NULL,
  [GradeScaleAlt_Key] [smallint] NULL,
  [EmployeeTypeAlt_Key] [smallint] NULL,
  [SOURCEALT_KEY] [varchar](30) NULL,
  [WorkFlowUserRoleAlt_Key] [smallint] NULL,
  [D2K_PSlt] [varchar](100) NULL
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO