CREATE TABLE [dbo].[Mod] (
  [ENTITYKEY] [int] NULL,
  [AccountEntityId] [nvarchar](50) NULL,
  [CustomerEntityId] [nvarchar](50) NULL,
  [SecurityType] [nvarchar](50) NULL,
  [CollateralType] [nvarchar](50) NULL,
  [SecurityAlt_Key] [nvarchar](50) NULL,
  [SecurityEntityID] [int] NULL,
  [Security_RefNo] [nvarchar](50) NULL,
  [SecurityNature] [nvarchar](50) NULL,
  [SecurityChargeTypeAlt_Key] [nvarchar](50) NULL,
  [CurrencyAlt_Key] [nvarchar](50) NULL,
  [EntryType] [nvarchar](50) NULL,
  [ScrCrError] [nvarchar](50) NULL,
  [InwardNo] [nvarchar](50) NULL,
  [Limitnode_Flag] [nvarchar](50) NULL,
  [RefCustomerId] [nvarchar](50) NULL,
  [RefSystemAcId] [nvarchar](50) NULL,
  [AuthorisationStatus] [nvarchar](50) NULL,
  [EffectiveFromTimeKey] [int] NULL,
  [EffectiveToTimeKey] [int] NOT NULL,
  [CreatedBy] [nvarchar](50) NOT NULL,
  [DateCreated] [datetime2] NOT NULL,
  [ModifiedBy] [nvarchar](50) NOT NULL,
  [DateModified] [nvarchar](50) NOT NULL,
  [ApprovedBy] [nvarchar](50) NOT NULL,
  [DateApproved] [nvarchar](50) NOT NULL,
  [D2Ktimestamp] [nvarchar](50) NOT NULL,
  [MocTypeAlt_Key] [nvarchar](50) NOT NULL,
  [MocStatus] [nvarchar](50) NOT NULL,
  [MocDate] [nvarchar](50) NOT NULL,
  [SecurityParticular] [nvarchar](50) NOT NULL,
  [OwnerTypeAlt_Key] [nvarchar](50) NOT NULL,
  [AssetOwnerName] [nvarchar](50) NOT NULL,
  [ValueAtSanctionTime] [nvarchar](50) NOT NULL,
  [BranchLastInspecDate] [nvarchar](50) NOT NULL,
  [SatisfactionNo] [nvarchar](50) NOT NULL,
  [SatisfactionDate] [nvarchar](50) NOT NULL,
  [BankShare] [nvarchar](50) NOT NULL,
  [ActionTakenRemark] [nvarchar](50) NOT NULL,
  [SecCharge] [nvarchar](50) NOT NULL,
  [CollateralID] [int] NULL,
  [UCICID] [int] NOT NULL,
  [CustomerName] [nvarchar](100) NOT NULL,
  [TaggingAlt_Key] [int] NOT NULL,
  [DistributionAlt_Key] [nvarchar](50) NOT NULL,
  [CollateralCode] [nvarchar](50) NOT NULL,
  [CollateralSubTypeAlt_Key] [int] NOT NULL,
  [CollateralOwnerShipTypeAlt_Key] [nvarchar](50) NOT NULL,
  [ChargeNatureAlt_Key] [nvarchar](50) NOT NULL,
  [ShareAvailabletoBankAlt_Key] [nvarchar](50) NOT NULL,
  [CollateralShareamount] [nvarchar](50) NOT NULL,
  [IfPercentagevalue_or_Absolutevalue] [nvarchar](50) NOT NULL,
  [CollateralValueatSanctioninRs] [nvarchar](50) NOT NULL,
  [CollateralValueasonNPAdateinRs] [nvarchar](50) NOT NULL,
  [ApprovedByFirstLevel] [nvarchar](50) NOT NULL,
  [DateApprovedFirstLevel] [nvarchar](50) NOT NULL,
  [ChangeField] [nvarchar](50) NOT NULL,
  [LiabID] [int] NOT NULL,
  [AssetID] [nvarchar](50) NOT NULL,
  [Segment] [int] NOT NULL,
  [CRE] [nvarchar](50) NOT NULL,
  [CollateralSubTypeDescription] [nvarchar](50) NOT NULL,
  [SeniorityofCharge] [int] NOT NULL,
  [SecurityStatus] [int] NOT NULL,
  [FDNo] [nvarchar](1) NULL,
  [ISINNo] [nvarchar](50) NULL,
  [FolioNo] [nvarchar](1) NULL,
  [QtyShares_MutualFunds_Bonds] [int] NOT NULL,
  [Line_No] [nvarchar](150) NOT NULL,
  [CrossCollateral_LiabID] [nvarchar](50) NOT NULL,
  [NameSecuPvd] [nvarchar](100) NULL,
  [PropertyAdd] [nvarchar](300) NULL,
  [PIN] [nvarchar](50) NOT NULL,
  [DtStockAudit] [nvarchar](50) NOT NULL,
  [SBLCIssuingBank] [nvarchar](1) NULL,
  [SBLCNumber] [nvarchar](1) NULL,
  [CurSBLCissued] [nvarchar](1) NULL,
  [SBLCFCY] [nvarchar](50) NOT NULL,
  [DtexpirySBLC] [nvarchar](50) NOT NULL,
  [DtexpiryLIC] [nvarchar](50) NOT NULL,
  [ModeOperation] [int] NOT NULL,
  [ExceApproval] [nvarchar](50) NOT NULL
)
ON [PRIMARY]
GO