CREATE TABLE [dbo].[AccountData_VisionPLUS_UAT_02] (
  [AccountBranchCode] [varchar](500) NULL,
  [FCR_CustomerID] [varchar](500) NULL,
  [SourceSystemCustomerID] [varchar](500) NULL,
  [AccountID] [varchar](500) NULL,
  [ContractRefNo] [varchar](500) NULL,
  [AccountOpenDate] [varchar](500) NULL,
  [FacilityCodeLineCode] [varchar](500) NULL,
  [FacilityLine] [varchar](500) NULL,
  [ProductCode] [varchar](500) NULL,
  [SectorCode] [varchar](500) NULL,
  [AccountSegmentCode] [varchar](500) NULL,
  [CurrentLimit] [varchar](500) NULL,
  [DisbAmount] [varchar](500) NULL,
  [CurrentLimitDate] [varchar](500) NULL,
  [CurrencyCode] [varchar](500) NULL,
  [DrawingPower] [varchar](500) NULL,
  [TotalBalanceOutstandingINR] [varchar](500) NULL,
  [BalanceInCurrency] [varchar](500) NULL,
  [PrincipalOutstanding] [varchar](500) NULL,
  [MaxDPD] [varchar](500) NULL,
  [TotalOverdueAmount ] [varchar](500) NULL,
  [OverdueSinceDate] [varchar](500) NULL,
  [PrincipalOverdue] [varchar](500) NULL,
  [PrincipalOverdueSinceDate] [varchar](500) NULL,
  [PrincipalOverdueDPD] [varchar](500) NULL,
  [InterestOverdue] [varchar](500) NULL,
  [InterestOverdueSinceDate] [varchar](500) NULL,
  [InterestOverdueSinceDPD] [varchar](500) NULL,
  [OtherOverdue] [varchar](500) NULL,
  [OtherOverdueSinceDate] [varchar](500) NULL,
  [OtherOverdueSinceDPD] [varchar](500) NULL,
  [SbaCaaTodDate] [varchar](500) NULL,
  [LastCreditDate] [varchar](500) NULL,
  [ContinuousExcessSinceDate] [varchar](500) NULL,
  [DPD_CCOD] [varchar](500) NULL,
  [FirstDtOfDisb] [varchar](500) NULL,
  [InterestRate] [varchar](500) NULL,
  [StockStatementDate] [varchar](500) NULL,
  [GovernmentGuaranteeAmount ] [varchar](500) NULL,
  [WriteOffAmount] [varchar](500) NULL,
  [UnAdjustSubSidy] [varchar](500) NULL,
  [AssetClass] [varchar](500) NULL,
  [NPADate] [varchar](500) NULL,
  [SourceSystemName] [varchar](500) NULL,
  [RelationshipNumber] [varchar](500) NULL,
  [AccountFlag] [varchar](500) NULL,
  [CommercialFlag] [varchar](500) NULL,
  [Liability] [varchar](500) NULL,
  [CD] [varchar](500) NULL,
  [Accountstatus] [varchar](500) NULL,
  [AccountBlkCode1] [varchar](500) NULL,
  [AccountBlkCode2] [varchar](500) NULL,
  [DateOfData] [varchar](500) NULL,
  [Data_Date] [varchar](500) NULL,
  [Etl_Date] [varchar](500) NULL,
  [RM_CODE] [varchar](500) NULL,
  [RM_NAME] [varchar](500) NULL,
  [TL_CODE] [varchar](500) NULL,
  [TL_NAME] [varchar](500) NULL,
  [FCRAccountStatus] [varchar](500) NULL,
  [Secured_FD_CC] [varchar](500) NULL,
  [Restr_Flag] [varchar](500) NULL,
  [Buyout_Code] [varchar](500) NULL
)
ON [PRIMARY]
GO