CREATE TABLE [dbo].[UploadCollateralDetail] (
  [Entity_Key] [int] IDENTITY,
  [SrNo] [varchar](max) NULL,
  [CollateralID] [varchar](max) NULL,
  [Action] [varchar](max) NULL,
  [LiabID] [varchar](max) NULL,
  [UCIC] [varchar](max) NULL,
  [CustName] [varchar](max) NULL,
  [AssetID] [varchar](max) NULL,
  [Segment] [varchar](max) NULL,
  [CRE] [varchar](max) NULL,
  [CollateralSubType] [varchar](max) NULL,
  [NameSecuPv] [varchar](max) NULL,
  [SeniorityCharge] [varchar](max) NULL,
  [SecurityStatus] [varchar](max) NULL,
  [FDNO] [varchar](max) NULL,
  [ISINNo_FolioNumber] [varchar](max) NULL,
  [QtyShares_MutualFunds_Bonds] [varchar](max) NULL,
  [Line_No] [varchar](max) NULL,
  [CrossCollateral_LiabID] [varchar](max) NULL,
  [PropertyAdd] [varchar](max) NULL,
  [PIN] [varchar](max) NULL,
  [DtStockAudit] [varchar](max) NULL,
  [SBLCIssuingBank] [varchar](max) NULL,
  [SBLCNumber] [varchar](max) NULL,
  [CurSBLCissued] [varchar](max) NULL,
  [SBLCFCY] [varchar](max) NULL,
  [DtexpirySBLC] [varchar](max) NULL,
  [DtexpiryLIC] [varchar](max) NULL,
  [ModeOperation] [varchar](max) NULL,
  [ExceApproval] [varchar](max) NULL,
  [ValSource_ExpBusinessRule] [varchar](max) NULL,
  [DtofValuation] [varchar](max) NULL,
  [ValueConsidered] [varchar](max) NULL,
  [SecondDtofValuation] [varchar](max) NULL,
  [SecondValuation] [varchar](max) NULL,
  [Expirydate] [varchar](max) NULL,
  [sheetname] [varchar](max) NULL,
  [ErrorMessage] [varchar](max) NULL,
  [ErrorinColumn] [varchar](max) NULL,
  [Srnooferroneousrows] [varchar](max) NULL
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO