CREATE TABLE [dbo].[DimReportParameter] (
  [DimReportCol_Key] [smallint] NULL,
  [DimReportColAlt_Key] [smallint] NULL,
  [ReportType] [smallint] NULL,
  [ReportMenuId] [smallint] NULL,
  [DisplayOrder] [smallint] NULL,
  [DisplayRowOrder] [smallint] NULL,
  [DisplayColumnOrder] [smallint] NULL,
  [Label] [varchar](50) NULL,
  [ControlType] [varchar](20) NULL,
  [DataType] [varchar](10) NULL,
  [Placeholder] [varchar](20) NULL,
  [Col_lg] [tinyint] NULL,
  [Col_md] [tinyint] NULL,
  [Col_sm] [tinyint] NULL,
  [IsDBPull] [bit] NULL,
  [ReferenceTable] [varchar](20) NULL,
  [ReferenceColumn] [varchar](20) NULL,
  [RefColumnValue] [varchar](50) NULL,
  [ReferenceTableCond] [varchar](100) NULL,
  [MasterTableValidCode] [varchar](10) NULL,
  [AuthorisationStatus] [varchar](2) NULL,
  [EffectiveFromTimeKey] [int] NULL,
  [EffectiveToTimeKey] [int] NULL,
  [CreatedBy] [varchar](20) NULL,
  [DateCreated] [smalldatetime] NULL,
  [ModifiedBy] [varchar](20) NULL,
  [DateModified] [smalldatetime] NULL,
  [ApprovedBy] [varchar](20) NULL,
  [DateApproved] [smalldatetime] NULL,
  [D2Ktimestamp] [timestamp],
  [ControlName] [varchar](50) NULL,
  [RoutineNo] [varchar](50) NULL,
  [RoutineArgument] [varchar](1000) NULL,
  [OnFormLoad] [varchar](5) NULL,
  [OnFormLoadParameter] [varchar](max) NULL,
  [SkipColumnInQuery] [char](1) NULL,
  [IsVisible] [bit] NULL,
  [IsMandatory] [bit] NULL,
  [IsF2Button] [bit] NULL,
  [IsCloseButton] [bit] NULL,
  [OnButtonClick] [varchar](10) NULL,
  [OnButtonClickParameter] [varchar](50) NULL,
  [MaxDateControlName] [varchar](50) NULL,
  [MinDateControlName] [varchar](50) NULL,
  [IsEditable] [bit] NULL
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO