CREATE TABLE [dbo].[AdvAcProjectDetail] (
  [EntityKey] [int] IDENTITY,
  [CustomerEntityID] [int] NOT NULL,
  [RefAccountEntityId] [varchar](max) NOT NULL,
  [ProjectId] [int] NULL,
  [ProjectName] [varchar](100) NULL,
  [ProjectCatgAlt_Key] [smallint] NULL,
  [FinancialClosureDt] [date] NULL,
  [PaidupCapital] [numeric] NULL,
  [ProjectParticular] [varchar](500) NULL,
  [OriginalEnvisagCompletionDt] [date] NULL,
  [RevisedCompletionDt] [date] NULL,
  [ActualCompletionDt] [date] NULL,
  [ProjectCostByInternalSource] [decimal](14, 2) NULL,
  [ProjectCostByDebt] [decimal](14, 2) NULL,
  [ProjectCostByEquity] [decimal](14, 2) NULL,
  [ProjectCostByOtherMeans] [decimal](14, 2) NULL,
  [ProjectCostByPPEquity] [decimal](14, 2) NULL,
  [ProjectCostByPPDebt] [decimal](14, 2) NULL,
  [ProjCostUptoPrevFinYear] [decimal](14, 2) NULL,
  [ProjCostCurFinYear] [decimal](14, 2) NULL,
  [ProjCostNextYear1] [decimal](14, 2) NULL,
  [ProjCostNextYear2] [decimal](14, 2) NULL,
  [ProjCostNextYear3] [decimal](14, 2) NULL,
  [ProjCostNextYear4] [decimal](14, 2) NULL,
  [ProjCostNextYear5] [decimal](14, 2) NULL,
  [ProjCostBeyond5Year] [decimal](14, 2) NULL,
  [ProjectCostRevisedByInternalSource] [decimal](14, 2) NULL,
  [ProjectCostRevisedByDebt] [decimal](14, 2) NULL,
  [ProjectCostRevisedByEquity] [decimal](14, 2) NULL,
  [ProjectCostRevisedByOtherMeans] [decimal](14, 2) NULL,
  [ProjectCurrentStatus] [varchar](250) NULL,
  [REVProjCostUptoPrevFinYear] [decimal](14, 2) NULL,
  [REVProjCostCurFinYear] [decimal](14, 2) NULL,
  [REVProjCostNextYear1] [decimal](14, 2) NULL,
  [REVProjCostNextYear2] [decimal](14, 2) NULL,
  [REVProjCostNextYear3] [decimal](14, 2) NULL,
  [REVProjCostNextYear4] [decimal](14, 2) NULL,
  [REVProjCostNextYear5] [decimal](14, 2) NULL,
  [REVProjCostBeyond5Year] [decimal](14, 2) NULL,
  [RevProjectCostByPPEquity] [decimal](14, 2) NULL,
  [RevProjectCostByPPDebt] [decimal](14, 2) NULL,
  [RefSystemacid] [varchar](30) NULL,
  [AuthorisationStatus] [varchar](2) NULL,
  [EffectiveFromTimeKey] [int] NULL,
  [EffectiveToTimeKey] [int] NOT NULL,
  [CreatedBy] [varchar](20) NULL,
  [DateCreated] [smalldatetime] NULL,
  [ModifiedBy] [varchar](20) NULL,
  [DateModified] [smalldatetime] NULL,
  [ApprovedBy] [varchar](20) NULL,
  [DateApproved] [smalldatetime] NULL,
  [D2Ktimestamp] [timestamp],
  [MocStatus] [char](1) NULL,
  [MocDate] [smalldatetime] NULL,
  [MocTypeAlt_Key] [int] NULL,
  [S4A_IMPLEMENTAION_FLG] [char](1) NULL,
  [S4A_REFERENCE_DATE] [date] NULL,
  [S4A_RESOLUTION_DATE] [date] NULL,
  [ProjectDelReason_AltKey] [smallint] NULL,
  [StandardRestruct_AltKey] [smallint] NULL,
  [CustomerId] [varchar](30) NULL,
  [AccountId] [varchar](30) NULL,
  [CustomerName] [varchar](100) NULL
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO