CREATE TABLE [dbo].[CollateralDetailUpload_Mod] (
  [SrNo] [int] NULL,
  [LiabID] [varchar](100) NULL,
  [UCIC] [varchar](16) NULL,
  [CustName] [varchar](200) NULL,
  [AssetID] [varchar](25) NULL,
  [Segment] [varchar](20) NULL,
  [CRE] [varchar](5) NULL,
  [CollateralSubType] [varchar](500) NULL,
  [NameSecuPv] [varchar](500) NULL,
  [SeniorityCharge] [varchar](50) NULL,
  [SecurityStatus] [varchar](25) NULL,
  [FDNO] [varchar](20) NULL,
  [ISINNo_FolioNumber] [varchar](25) NULL,
  [QtyShares_MutualFunds_Bonds] [bigint] NULL,
  [Line_No] [varchar](300) NULL,
  [CrossCollateral_LiabID] [varchar](500) NULL,
  [PropertyAdd] [varchar](2500) NULL,
  [PIN] [int] NULL,
  [DtStockAudit] [date] NULL,
  [SBLCIssuingBank] [varchar](100) NULL,
  [SBLCNumber] [varchar](25) NULL,
  [CurSBLCissued] [varchar](15) NULL,
  [SBLCFCY] [decimal](16, 2) NULL,
  [DtexpirySBLC] [date] NULL,
  [DtexpiryLIC] [date] NULL,
  [ModeOperation] [varchar](15) NULL,
  [ExceApproval] [varchar](15) NULL,
  [ValSource_ExpBusinessRule] [varchar](500) NULL,
  [DtofValuation] [date] NULL,
  [ValueConsidered] [decimal](16, 2) NULL,
  [SecondDtofValuation] [date] NULL,
  [SecondValuation] [decimal](16, 2) NULL,
  [UploadID] [int] NULL,
  [EffectiveFromTimeKey] [int] NULL,
  [EffectiveToTimeKey] [int] NULL,
  [AuthorisationStatus] [varchar](5) NULL,
  [Changes] [varchar](200) NULL,
  [Remark] [varchar](200) NULL,
  [CreatedBy] [varchar](50) NULL,
  [DateCreated] [datetime] NULL,
  [ModifiedBy] [varchar](50) NULL,
  [DateModified] [datetime] NULL,
  [ApprovedBy] [varchar](50) NULL,
  [DateApproved] [datetime] NULL,
  [CollateralID] [varchar](30) NULL,
  [Expirydate] [date] NULL,
  [Action] [varchar](1) NULL,
  [CollateralIDModification] [varchar](30) NULL
)
ON [PRIMARY]
GO