CREATE TABLE [PREMOC].[CustomerCal] (
  [EntityKey] [bigint] IDENTITY,
  [BranchCode] [varchar](20) NULL,
  [UCIF_ID] [varchar](50) NULL,
  [UcifEntityID] [int] NULL,
  [CustomerEntityID] [int] NULL,
  [ParentCustomerID] [varchar](50) NULL,
  [RefCustomerID] [varchar](50) NULL,
  [SourceSystemCustomerID] [varchar](50) NULL,
  [CustomerName] [varchar](225) SPARSE NULL,
  [CustSegmentCode] [varchar](10) SPARSE NULL,
  [ConstitutionAlt_Key] [int] SPARSE NULL,
  [PANNO] [varchar](12) SPARSE NULL,
  [AadharCardNO] [varchar](14) SPARSE NULL,
  [SrcAssetClassAlt_Key] [smallint] SPARSE NULL,
  [SysAssetClassAlt_Key] [smallint] SPARSE NULL,
  [SplCatg1Alt_Key] [int] SPARSE NULL,
  [SplCatg2Alt_Key] [int] SPARSE NULL,
  [SplCatg3Alt_Key] [int] SPARSE NULL,
  [SplCatg4Alt_Key] [int] SPARSE NULL,
  [SMA_Class_Key] [int] SPARSE NULL,
  [PNPA_Class_Key] [int] SPARSE NULL,
  [PrvQtrRV] [decimal](18, 2) NULL,
  [CurntQtrRv] [decimal](18, 2) NULL,
  [TotProvision] [decimal](16, 2) SPARSE NULL,
  [BankTotProvision] [decimal](16, 2) NULL,
  [RBITotProvision] [decimal](18, 2) NULL,
  [SrcNPA_Dt] [date] SPARSE NULL,
  [SysNPA_Dt] [date] SPARSE NULL,
  [DbtDt] [date] SPARSE NULL,
  [DbtDt2] [date] SPARSE NULL,
  [DbtDt3] [date] SPARSE NULL,
  [LossDt] [date] SPARSE NULL,
  [MOC_Dt] [date] SPARSE NULL,
  [ErosionDt] [date] SPARSE NULL,
  [SMA_Dt] [date] SPARSE NULL,
  [PNPA_Dt] [date] SPARSE NULL,
  [ProcessingDt] [date] SPARSE NULL,
  [Asset_Norm] [varchar](15) SPARSE NULL,
  [FlgDeg] [char](1) SPARSE NULL,
  [FlgUpg] [char](1) SPARSE NULL,
  [FlgMoc] [char](1) SPARSE NULL,
  [FlgSMA] [char](1) SPARSE NULL,
  [FlgProcessing] [char](1) SPARSE NULL,
  [FlgErosion] [char](1) SPARSE NULL,
  [FlgPNPA] [char](1) SPARSE NULL,
  [FlgPercolation] [char](1) SPARSE NULL,
  [FlgInMonth] [char](1) SPARSE NULL,
  [FlgDirtyRow] [char](1) SPARSE NULL,
  [DegDate] [date] SPARSE NULL,
  [EffectiveFromTimeKey] [int] NULL,
  [EffectiveToTimeKey] [int] NULL,
  [CommonMocTypeAlt_Key] [smallint] SPARSE NULL,
  [InMonthMark] [char](1) SPARSE NULL,
  [MocStatusMark] [char](1) SPARSE NULL,
  [SourceAlt_Key] [int] NULL,
  [BankAssetClass] [varchar](10) NULL,
  [Cust_Expo] [decimal](18, 2) NULL,
  [MOCReason] [varchar](500) NULL,
  [AddlProvisionPer] [decimal](6, 2) NULL,
  [FraudDt] [date] NULL,
  [FraudAmount] [decimal](18, 2) NULL,
  [DegReason] [varchar](1000) NULL,
  [IMAXID_CCube] [varchar](100) NULL,
  [DateOfData] [date] NULL,
  [CustMoveDescription] [varchar](10) NULL,
  [TotOsCust] [decimal](18, 2) NULL,
  [moctype] [varchar](200) NULL,
  [CustomerPartnerSegment] [varchar](100) NULL
)
ON [PRIMARY]
GO