CREATE TABLE [pro].[COBORROWERDETAILS_BKP_20250329] (
  [CoBorrowerID] [nvarchar](45) NULL,
  [RefCustomerID] [varchar](50) NULL,
  [APPLID] [nvarchar](30) NULL,
  [AGREEMENTNO] [nvarchar](30) NULL,
  [FLAG] [char](1) NULL,
  [CO_APPLICANT_FIN_CUST_ID] [nvarchar](30) NULL,
  [CO_APPLICANT_FCR_CUST_ID] [nvarchar](45) NULL,
  [CO_APPLICANT_UCIC] [nvarchar](360) NULL,
  [CO_APPLICANT_NAME] [nvarchar](300) NULL,
  [APPLICANT_FIN_CUST_ID] [nvarchar](30) NULL,
  [APPLICANT_FCR_CUST_ID] [nvarchar](45) NULL,
  [APPLICANT_UCIC] [nvarchar](360) NULL,
  [APPLICANT_NAME] [nvarchar](300) NULL,
  [AuthorisationStatus] [char](2) NULL,
  [EffectiveFromTimeKey] [int] NOT NULL,
  [EffectiveToTimeKey] [int] NOT NULL,
  [CreatedBy] [varchar](20) NULL,
  [DateCreated] [smalldatetime] NULL,
  [ModifiedBy] [varchar](20) NULL,
  [DateModified] [smalldatetime] NULL,
  [ApprovedBy] [varchar](20) NULL,
  [DateApproved] [smalldatetime] NULL,
  [FlgDeg] [char](1) NULL,
  [DegDate] [date] NULL,
  [FlgUpg] [char](1) NULL,
  [UpgDate] [date] NULL,
  [SourceSystemCustomerID] [varchar](50) NULL,
  [UCIF_ID] [varchar](50) NULL,
  [PANNO] [varchar](12) NULL,
  [Co_NPADate] [date] NULL,
  [Co_Assetclassalt_key] [int] NULL,
  [Pri_NPADate] [date] NULL,
  [Pri_Assetclassalt_key] [int] NULL
)
ON [PRIMARY]
GO