CREATE TABLE [pro].[DataToClient_DegradePNPA] (
  [EntityKey] [int] IDENTITY,
  [DateOfData] [date] NULL,
  [BranchCode] [varchar](20) NULL,
  [UCIF_ID] [varchar](50) NULL,
  [FCRCustomerId] [varchar](30) NULL,
  [CustomerName] [varchar](225) NULL,
  [SrcSystemCustomerID] [varchar](30) NULL,
  [PANNO] [varchar](12) SPARSE NULL,
  [AadharCardNO] [varchar](14) SPARSE NULL,
  [SrcAssetClassCust] [varchar](10) NULL,
  [SrcAssetClassCustDesc] [varchar](14) SPARSE NULL,
  [ENPA_AssetClassCust] [varchar](14) SPARSE NULL,
  [SrcNPA_DtCust] [date] SPARSE NULL,
  [ENPA_NPA_DtCust] [date] SPARSE NULL,
  [CustomerAcID/Contact Ref. No] [varchar](30) NULL,
  [SrcSystemName] [varchar](14) SPARSE NULL,
  [FacilityType] [varchar](10) NULL,
  [LineCode] [varchar](30) NULL,
  [ProductCode] [varchar](10) NULL,
  [ProductDescription] [varchar](50) NULL,
  [CurrentLimit] [decimal](14) NULL,
  [ContiExcessDt] [date] NULL,
  [StockStDt] [date] NULL,
  [IntNotServicedDt] [date] NULL,
  [ReviewDueDt] [date] NULL,
  [OverDueSinceDt] [date] NULL,
  [DPD_Overdrawn] [int] NULL,
  [DPD_StockStmt] [int] NULL,
  [DPD_IntService] [int] NULL,
  [DPD_Renewal] [int] NULL,
  [DPD_Overdue] [int] NULL,
  [DPD_Max] [int] NULL,
  [RefPeriodOverDrawn] [smallint] SPARSE NULL,
  [RefPeriodStkStatement] [smallint] SPARSE NULL,
  [RefPeriodIntService] [smallint] SPARSE NULL,
  [RefPeriodReview] [smallint] SPARSE NULL,
  [RefPeriodOverdue] [smallint] SPARSE NULL,
  [DegReason] [varchar](max) NULL,
  [PNPA_Reason] [varchar](max) NULL,
  [SMA_Class] [varchar](5) NULL,
  [SMA_Reason] [varchar](max) NULL,
  [FLGDEG] [char](1) SPARSE NULL,
  [FLGUPG] [char](1) SPARSE NULL,
  [FlgPNPA] [char](1) SPARSE NULL,
  [FlgSMA] [char](1) SPARSE NULL,
  [Balance] [decimal](18, 2) NULL,
  [Overdue] [decimal](18, 2) NULL,
  [SrcAssetClassAccount] [varchar](14) SPARSE NULL,
  [SrcAssetClassAccountDesc] [varchar](14) NULL,
  [ENPA_AssetClassAccount] [varchar](14) SPARSE NULL,
  [SrcNpaDtAccount] [date] NULL,
  [ENPA_NpaDtAccount] [date] NULL,
  [TotalProv] [decimal](18, 2) NULL,
  [CommercialFlag] [int] NULL,
  [AccountFlag] [varchar](20) NULL,
  [Liability] [varchar](20) NULL,
  [CD] [varchar](20) NULL,
  [AccountStatus] [varchar](30) NULL,
  [Timekey] [int] NULL,
  [ExposureType] [varchar](20) NULL,
  [SecurityAmount] [decimal](18, 2) NULL,
  [DebitSinceDt] [date] NULL,
  [POS] [decimal](18, 2) NULL,
  [Cust_DPD] [int] NULL,
  [IntBucket_1_30] [numeric](16) NULL,
  [IntBucket_31_60] [numeric](16) NULL,
  [IntBucket_61_89] [numeric](16) NULL
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO