CREATE TABLE [pro].[OverDueData_Component] (
  [EntityKey] [int] IDENTITY,
  [AccountEntityID] [int] SPARSE NULL,
  [UcifEntityID] [int] SPARSE NULL,
  [CustomerEntityID] [int] NULL,
  [LiabilityId] [varchar](100) NULL,
  [RefCustomerID] [varchar](100) NULL,
  [CustomerAcID] [varchar](75) NULL,
  [CurrencyCode] [varchar](3) NULL,
  [OverdueComponent] [varchar](35) NULL,
  [Dpd] [int] NULL,
  [OverDueSinceDt] [date] NULL,
  [OverdueAmountDue] [decimal](16, 2) NULL,
  [OverdueAmountSettled] [decimal](16, 2) NULL,
  [DpdAmountContractCurrency] [decimal](16, 2) NULL,
  [DpdAmountLcy] [decimal](16, 2) NULL,
  [RegionName] [varchar](200) NULL,
  [ClusterName] [varchar](200) NULL,
  [LiabilityName] [varchar](250) NULL,
  [CustomerName] [varchar](250) NULL,
  [SegmentCode] [varchar](27) NULL,
  [RmCode] [varchar](100) NULL,
  [ProductDescription] [varchar](255) NULL,
  [BranchCode1] [varchar](20) NULL,
  [CustomerRating] [varchar](30) NULL,
  [RmName] [varchar](500) NULL,
  [TlCode] [varchar](100) NULL,
  [TlName] [varchar](250) NULL,
  [BusinessSegment] [varchar](100) NULL,
  [PSCode] [varchar](100) NULL,
  [BranchCode] [int] NULL,
  [BranchName] [varchar](400) NULL,
  [LiabilityRmCode] [varchar](250) NULL,
  [AssetRmCode] [varchar](250) NULL,
  [BusinessTlSegment] [varchar](250) NULL,
  [IndustrySegment] [varchar](250) NULL,
  [UCIF_ID] [varchar](50) NULL,
  [PANNO] [varchar](12) NULL,
  [DateOfData] [date] NULL,
  [EffectiveFromTimeKey] [int] NULL,
  [EffectiveToTimeKey] [int] NULL
)
ON [PRIMARY]
GO